### ISSUE TITLE
Rewrite existing for-loops in App.js with forEach() method and/or arrow notation

### ISSUE THREAD

**Issue by dongskyler** [Badwater-Apps/intelli-trip-planner#18]
Rewrite existing for-loops in src/html/app/intelligent-trip-planner/Apps.js with JavaScript’s forEach() method and/or arrow notations, wherever appropriate.

As far as I remember, most for-loops (if not all) can be rewritten with object-oriented and/or functional styles.

For example: 

```
for (let i = 0; i < foodArray.length; i++) {
  console.log(`i value: ${i} | Food Name:`, foodArray[i]);
}

// Result:
// i value: 0 | Food Name: { name: 'Burrito' }
// i value: 1 | Food Name: { name: 'Pizza' }
// i value: 2 | Food Name: { name: 'Burger' }
// i value: 3 | Food Name: { name: 'Pasta' }
```

The code above can be rewritten as:

```
foodArray.forEach((food, index) => {
  console.log(`i value: ${index} | Food Name:`, food);
});

// Result:
// i value: 0 | Food Name: { name: 'Burrito' }
// i value: 1 | Food Name: { name: 'Pizza' }
// i value: 2 | Food Name: { name: 'Burger' }
// i value: 3 | Food Name: { name: 'Pasta' }
```

Reference: https://alligator.io/js/foreach-vs-for-loops/

**Comment by tangaw** [comment]
Working on this and learning on the fly.
Seems like the most obvious use case is when you want to iterate over arrays. At first few glances, it doesn't appear that all for-loops can be easily replaced with forEach loops.
Upping this to a `Complexity: 2`.
